### ISSUE TITLE
png to raw

### ISSUE THREAD

**Issue by maziyao** [sangjela/RaspberryPiPicoSt7789#1]
hello,how change png to raw

**Comment by sangjela** [comment]
> hello,how change png to raw

Good Day!
You can change png to raw by run below python file.

https://github.com/sangjela/RaspberryPiPicoSt7789/blob/main/util/png2raw.py
#L16 infile = "utaha_240.png" // change name for input file
#L18 outfile = "utaha_240.raw" // change name for output file, 16bit color result

**Comment by maziyao** [comment]
thanks,but I have this problem

Could not write next block after having written 7168 bytes to /picseq/utaha_240_456.raw
Make sure your device's filesystem has enough free space. (When overwriting a file, the old content may occupy space until the end of the operation.)

THONNY FAILED TO EXECUTE COMMAND upload


SCRIPT:
__W(b'fffffffffffffffffffffffefffbfffdffffffffffffffffffffffffffffffff18c3294429652945528a5aeb4a49212421042104210420e421042104210429042924316541c6420741c7526a420939a7524952494a284a284208420841e741e841e8420942093a094209420931a629242124210441c78b2a6aa941c7526a4a6a42294229424942494a6a4a6a52ab8c51f79effffffffffffd69a634d4a6a632ca53394b1a513bdd6ce58d699d6bad699c6179cf3738d4a4839c731a631a739e831a7318631a6318631a631a631a631a673ae84314a8a422839a739c739e74a69bdd6ef5cef7ce71bffffef5d52ca31a631a639a6318631864a49630b5aca630b6b6d84309cd27bce73aea513bdb6ef7dffffffffd699ad54b574bdd6bdd67bce4a2842284a2852697b8cde36ffbcffffc618bdd6ce58d679d679d679d699d69adebadebadebadedadedadedadefae6daeefbf77dffffffffffffffffffffffffffffffffffffffffffffffffffffffffeed8dd70f632ff16ffbcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6d7ff38fe73fe52fe72fe73f653f632f653fe93ff16fffefffffffffffffffffffcfff8fff9fffefffffffffffffffffffffffffffffffffffffffffffffffffffbfffcffffffffffffffffffffffffffffffffffff18c318e33164210342285acb318620e420e320e320e420e4210321042924294429442944318541e74a07528a5acb41c7524952494a284a0841e841e739e739c739a739c731a731a731a739c7316629452124210449e7938b8b6b41c64207424839e83a084228420839e739c739e8528a9cf4f79effffffffd6bb6b8e4a6a5aeb9cf2c617ad34a514b596bdf6be1794b2632c4a4939e742084a4941e731a731a7298631863186298631653166318639a67b6e5aeb31a631a631a631a639c731a6738ee73cef5ce73cffffb5b639c73186318631863186318641e75aca528a5aeb632c84109cb27bce738d9cd2b5b6ef7dffffffffd679ad54b574c5d68c3041e739a739c741e741e75a89acf2f77cffdec5f7bdd6ce59d679d679d679d699d699de99de99debadebadedadedae6dae6dae6fbf79dffffffffffffffffffffffffffffffffffffffffffffffffffffffffeeb8dd50f632ff37ffddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5af716ff36fe72fe72f672f632edf2f612fe53fe93ff58fffffffffffffffffffdfff7fff8fffdfffffffffffffffffffffffffffffffffffffffffffffffffffcfffbffffffffffffffffffffffffffffffffffffffff10c218c22924292439c74209210420e420e320e318e320e420e3210429242924')

STDOUT:


STDERR:
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "<stdin>", line 5, in __W

OSError: 28

**Comment by sangjela** [comment]
> thanks,but I have this problem
> 
> Could not write next block after having written 7168 bytes to /picseq/utaha_240_456.raw
> Make sure your device's filesystem has enough free space. (When overwriting a file, the old content may occupy space until the end of the operation.)
> 
> THONNY FAILED TO EXECUTE COMMAND upload
> SCRIPT:
> __W(b'fffffffffff.......20e3210429242924')
> STDOUT:
> STDERR:
> Traceback (most recent call last):
> 
> File "", line 1, in
> File "", line 5, in __W
> 
> OSError: 28

Hmm...
I think... at least, you can check below...
1. at first... you have enough space for disk write? Can you save or move Big file like some movie to the target folder?
2. my case, I run this on my mac or PC, it Have very very large disk, not on raspberry pi pico.
